"""
auto_debugger — Memory Dump Analysis Framework

Usage
-----
    python main.py <dump_folder> <product_id> [--repl]

Arguments
---------
dump_folder : str
    Path to a folder containing:
      - One or more *.dump files  (memory dump)
      - Exactly one *.map file    (memory map generated by firmware build)

product_id : str
    Product identifier — must match a subfolder under products/.
    Example: "epdc", "ufs", "nvme"
    The engine loads products/<product_id>/product.py automatically.

--repl : optional flag
    After running all analyzers, drop into an interactive GDB-style REPL
    for manual inspection.
"""

import sys
import importlib.util
from pathlib import Path

from engine.loader   import load_dump, load_map, find_map_file
from engine.api      import DumpAnalyzer
from engine.registry import ModuleRegistry
from engine.repl     import DebugREPL


def _load_product(product_id: str) -> object:
    """
    Resolves product_id → products/<product_id>/product.py and imports it.
    The module must define a register(registry: ModuleRegistry) function.
    """
    product_path = Path("products") / product_id / "product.py"
    if not product_path.exists():
        available = sorted(
            p.name for p in Path("products").iterdir()
            if p.is_dir() and (p / "product.py").exists()
        ) if Path("products").exists() else []
        raise FileNotFoundError(
            f"Product '{product_id}' not found.\n"
            f"Expected: {product_path}\n"
            f"Available products: {available if available else '(none)'}"
        )

    spec   = importlib.util.spec_from_file_location(f"products.{product_id}.product", product_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    if not hasattr(module, "register"):
        raise AttributeError(
            f"products/{product_id}/product.py must define a "
            f"register(registry: ModuleRegistry) function."
        )
    return module


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    dump_folder = sys.argv[1]
    product_id  = sys.argv[2]
    interactive = "--repl" in sys.argv

    # ── Load dump + map ────────────────────────────────────────────────────────
    map_file = find_map_file(dump_folder)
    print(f"[INFO] Using map: {map_file}")

    regions  = load_map(map_file)
    mem      = load_dump(dump_folder)
    analyzer = DumpAnalyzer(mem, regions)

    # ── Load product + register modules ───────────────────────────────────────
    print(f"[INFO] Loading product '{product_id}'...")
    product  = _load_product(product_id)
    registry = ModuleRegistry()
    product.register(registry)

    registered = [m.name for m in registry._modules]
    print(f"[INFO] Registered modules: {registered}\n")

    # ── Run all analyzers ──────────────────────────────────────────────────────
    for mod_name, fn in registry._all_analyzers():
        try:
            fn(analyzer)
        except Exception as e:
            print(f"\n[ERROR] {mod_name}.{fn.__name__} failed: {e}")

    # ── Optional REPL (always after analysis) ─────────────────────────────────
    if interactive:
        DebugREPL(analyzer, registry._analyzer_map()).run()


if __name__ == "__main__":
    main()
