# AUTO-GENERATED — DO NOT EDIT MANUALLY
# Generated by struct_gen (from firmware headers) or ipxact_to_structs.py (from IP-XACT)
#
# To regenerate:
#   make structs.py                              (from firmware headers via struct_gen)
#   python ipxact_to_structs.py <file.xml> structs.py  (from IP-XACT)
#
# Each class mirrors its C++ counterpart exactly.
# _pack_ must match the firmware struct's packing pragma.

import ctypes

# ── Example — replace with your actual generated struct ───────────────────────
#
# class TagManagerSfr(ctypes.LittleEndianStructure):
#     _pack_ = 4
#     _fields_ = [
#         ("occupied_tags", ctypes.c_uint32 * 48),   # bitmap array
#         ("tag_count",     ctypes.c_uint32, 10),    # 10-bit bitfield
#         ("free_count",    ctypes.c_uint32, 10),    # 10-bit bitfield
#         ("error_flags",   ctypes.c_uint32,  4),    # 4-bit bitfield
#         ("reserved",      ctypes.c_uint32,  8),    # padding
#     ]
#
# assert ctypes.sizeof(TagManagerSfr) == 200, \
#     f"TagManagerSfr size mismatch: got {ctypes.sizeof(TagManagerSfr)}, expected 200"
